### ISSUE TITLE
BlueMap support not working

### ISSUE THREAD

**Issue by dcepil** [Xyness/SimpleClaimSystem#16]
Hi,

First of all, I'm really liking this plugin, so thanks for the work done!

System info:
- BlueMap 5.4 Paper
- SimpleClaimSystem 1.11.6.2

After creating a claim, with BlueMap installed and BlueMap support enabled in the config, the following exception is thrown in the server's console:
```
[12:20:56 WARN]: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/flowpowered/math/vector/Vector2d
[12:20:56 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[12:20:56 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[12:20:56 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[12:20:56 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[12:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[12:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[12:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[12:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[12:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[12:20:56 WARN]: Caused by: java.lang.NoClassDefFoundError: com/flowpowered/math/vector/Vector2d
[12:20:56 WARN]:        at SimpleClaimSystem.jar//fr.xyness.SCS.Support.ClaimBluemap.lambda$createClaimZone$2(ClaimBluemap.java:116)
[12:20:56 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[12:20:56 WARN]:        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
[12:20:56 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[12:20:56 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
[12:20:56 WARN]:        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[12:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[12:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(ForkJoinPool.java:1395)
[12:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:2104)
[12:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:420)
[12:20:56 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:668)
[12:20:56 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
[12:20:56 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
[12:20:56 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[12:20:56 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[12:20:56 WARN]:        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
[12:20:56 WARN]:        at SimpleClaimSystem.jar//fr.xyness.SCS.Support.ClaimBluemap.createClaimZone(ClaimBluemap.java:106)
[12:20:56 WARN]:        at SimpleClaimSystem.jar//fr.xyness.SCS.ClaimMain.lambda$addClaimChunk$180(ClaimMain.java:3730)
[12:20:56 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[12:20:56 WARN]:        ... 6 more
[12:20:56 WARN]: Caused by: java.lang.ClassNotFoundException: com.flowpowered.math.vector.Vector2d
[12:20:56 WARN]:        ... 25 more
```

Obviously, BlueMap never gets updated with the claim area info, since this throws. Maybe worth mentioning that it doesn't matter if it's a brand new `/claim`, autoclaim or adding a chunk via `/claim addchunk`. The only time this hasn't been thrown from what I've tested is when I merged 4 claims into 1 via `/claim merge`, I suppose because no new claims were created.

EDIT: Even worse, seems like the entire chunk claiming flow is disrupted by this uncaught (?) exception, since after creating a claim, its border and the message telling the player how to access the claim's settings are not shown, and seems like fully saving the world, shutting the server down gracefully, and starting it back up results in the claim being removed. I have now disabled BlueMap support in config and claiming seems to be working fine again.

**Comment by Xyness** [comment]
Hi, thanks! Thank's for reporting too, i'll fix the bluemap support in the next update :)

**Comment by sluhtie** [comment]
Is there any updates on this?

**Comment by Xyness** [comment]
Hi, its fixed on the latest update, thanks!
