### ISSUE TITLE
Looks like this is a warning caused by a network issue, and it keeps popping up in the console.

### ISSUE THREAD

**Issue by Cqmmls** [Xyness/SimpleClaimSystem#2]
[01:36:30 WARN]: java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/gstwstwet
[01:36:30 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1994)
[01:36:30 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[01:36:30 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[01:36:30 WARN]:        at SimpleClaimSystem.jar//fr.xyness.SCS.Others.MinecraftSkinUtil.getUUID(MinecraftSkinUtil.java:61)
[01:36:30 WARN]:        at SimpleClaimSystem.jar//fr.xyness.SCS.Others.MinecraftSkinUtil.createPlayerHead(MinecraftSkinUtil.java:126)
[01:36:30 WARN]:        at SimpleClaimSystem.jar//fr.xyness.SCS.Others.MinecraftSkinUtil.lambda$loadPlayersHead$0(MinecraftSkinUtil.java:158)
[01:36:30 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[01:36:30 WARN]:        at SimpleClaimSystem.jar//fr.xyness.SCS.Others.MinecraftSkinUtil.lambda$loadPlayersHead$1(MinecraftSkinUtil.java:158)
[01:36:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:91)
[01:36:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[01:36:30 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:36:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[01:36:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[01:36:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[01:36:32 WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.mojang.com/users/profiles/minecraft/狗二胡
[01:36:32 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998)
[01:36:32 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[01:36:32 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[01:36:32 WARN]:        at SimpleClaimSystem.jar//fr.xyness.SCS.Others.MinecraftSkinUtil.getUUID(MinecraftSkinUtil.java:61)
[01:36:32 WARN]:        at SimpleClaimSystem.jar//fr.xyness.SCS.Others.MinecraftSkinUtil.createPlayerHead(MinecraftSkinUtil.java:126)
[01:36:32 WARN]:        at SimpleClaimSystem.jar//fr.xyness.SCS.Others.MinecraftSkinUtil.lambda$loadPlayersHead$0(MinecraftSkinUtil.java:158)
[01:36:32 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[01:36:32 WARN]:        at SimpleClaimSystem.jar//fr.xyness.SCS.Others.MinecraftSkinUtil.lambda$loadPlayersHead$1(MinecraftSkinUtil.java:158)
[01:36:32 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:91)
[01:36:32 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[01:36:32 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:36:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[01:36:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[01:36:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Xyness** [comment]
Hi, thank's for reporting! I'm working on this issue

**Comment by Xyness** [comment]
@Cqmmls Hi, its fixed with the latest version of SimpleClaimSystem 1.9.0.4

**Comment by Cqmmls** [comment]
Thanks, I've been using this plugin.
